services:
  api:
    build: .
    container_name: api-mexico-estados
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CONNECTION_URL=${CONNECTION_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
    restart: always

  seed:
    build: .
    container_name: api-mexico-seed
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CONNECTION_URL=${CONNECTION_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
    command: npm run seed
